name: dadd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.2
  firebase_app_check: ^0.3.1+5
  persistent_bottom_nav_bar: ^6.2.1
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/avatar.jpg
    - assets/image/background.jpg
    - assets/image/background2.png
    - assets/image/logo.png
    - assets/image/google_logo.png


flutter_icons:
  android: true
  image_path: "assets/icon/icon_app.png"